### ISSUE TITLE
feat: Deno・CLI・Typescript周りの設定(続き)

### ISSUE THREAD

**Issue by melumuccu** [hacksaw-org/investment-app#16]
# ToDo

- [x] git log などの出力で日本語が文字化けしている
- [x] pecoなど入れて快適にする
- [x] strict: true
- [x] [pr がマージされた時に issue が閉じない問題](https://hacksaw-www.slack.com/archives/C04Q149801K/p1678743917261909)
- [ ] Deno の formatter などの設定
